#ifndef HWPE_NVDLA_ALL_TRACES_H
#define HWPE_NVDLA_ALL_TRACES_H



// Header file generated by the 'trace_test_to_c.py' Python
// script which generates header files required for testing NVDLA.
// Authors:
//      - Luka Macan <luka.macan@fer.hr>
//      - Mihael Kovač <mihael.kovac@fer.hr>






#ifdef CDP_1X1X1_LRN3_INT8_0
#define HWPE_NVDLA_TRACE cdp_1x1x1_lrn3_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/cdp_1x1x1_lrn3_int8_0/cdp_1x1x1_lrn3_int8_0.h"
#define TRACE_INPUT_DATA cdp_1x1x1_lrn3_int8_0_data
#define TRACE_OUTPUT_SPACE cdp_1x1x1_lrn3_int8_0_space
#endif // CDP_1X1X1_LRN3_INT8_0

#ifdef CDP_1X1X31_LRN3_INT8_0
#define HWPE_NVDLA_TRACE cdp_1x1x31_lrn3_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/cdp_1x1x31_lrn3_int8_0/cdp_1x1x31_lrn3_int8_0.h"
#define TRACE_INPUT_DATA cdp_1x1x31_lrn3_int8_0_data
#define TRACE_OUTPUT_SPACE cdp_1x1x31_lrn3_int8_0_space
#endif // CDP_1X1X31_LRN3_INT8_0

#ifdef CDP_33X17X34_LRN5_INT8_0
#define HWPE_NVDLA_TRACE cdp_33x17x34_lrn5_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/cdp_33x17x34_lrn5_int8_0/cdp_33x17x34_lrn5_int8_0.h"
#define TRACE_INPUT_DATA cdp_33x17x34_lrn5_int8_0_data
#define TRACE_OUTPUT_SPACE cdp_33x17x34_lrn5_int8_0_space
#endif // CDP_33X17X34_LRN5_INT8_0

#ifdef CDP_8X8X32_LRN3_INT8_0
#define HWPE_NVDLA_TRACE cdp_8x8x32_lrn3_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/cdp_8x8x32_lrn3_int8_0/cdp_8x8x32_lrn3_int8_0.h"
#define TRACE_INPUT_DATA cdp_8x8x32_lrn3_int8_0_data
#define TRACE_OUTPUT_SPACE cdp_8x8x32_lrn3_int8_0_space
#endif // CDP_8X8X32_LRN3_INT8_0

#ifdef CDP_8X8X32_LRN3_INT8_1
#define HWPE_NVDLA_TRACE cdp_8x8x32_lrn3_int8_1
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/cdp_8x8x32_lrn3_int8_1/cdp_8x8x32_lrn3_int8_1.h"
#define TRACE_INPUT_DATA cdp_8x8x32_lrn3_int8_1_data
#define TRACE_INPUT_DATA_1 cdp_8x8x32_lrn3_int8_1_data_1
#endif // CDP_8X8X32_LRN3_INT8_1

#ifdef CDP_8X8X32_LRN3_INT8_2
#define HWPE_NVDLA_TRACE cdp_8x8x32_lrn3_int8_2
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/cdp_8x8x32_lrn3_int8_2/cdp_8x8x32_lrn3_int8_2.h"
#define TRACE_INPUT_DATA cdp_8x8x32_lrn3_int8_2_data
#define TRACE_OUTPUT_SPACE cdp_8x8x32_lrn3_int8_2_space
#endif // CDP_8X8X32_LRN3_INT8_2

#ifdef CDP_8X8X32_LRN5_INT8_0
#define HWPE_NVDLA_TRACE cdp_8x8x32_lrn5_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/cdp_8x8x32_lrn5_int8_0/cdp_8x8x32_lrn5_int8_0.h"
#define TRACE_INPUT_DATA cdp_8x8x32_lrn5_int8_0_data
#define TRACE_OUTPUT_SPACE cdp_8x8x32_lrn5_int8_0_space
#endif // CDP_8X8X32_LRN5_INT8_0

#ifdef CDP_8X8X32_LRN7_INT8_0
#define HWPE_NVDLA_TRACE cdp_8x8x32_lrn7_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/cdp_8x8x32_lrn7_int8_0/cdp_8x8x32_lrn7_int8_0.h"
#define TRACE_INPUT_DATA cdp_8x8x32_lrn7_int8_0_data
#define TRACE_OUTPUT_SPACE cdp_8x8x32_lrn7_int8_0_space
#endif // CDP_8X8X32_LRN7_INT8_0

#ifdef CDP_8X8X32_LRN9_INT8_0
#define HWPE_NVDLA_TRACE cdp_8x8x32_lrn9_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/cdp_8x8x32_lrn9_int8_0/cdp_8x8x32_lrn9_int8_0.h"
#define TRACE_INPUT_DATA cdp_8x8x32_lrn9_int8_0_data
#define TRACE_OUTPUT_SPACE cdp_8x8x32_lrn9_int8_0_space
#endif // CDP_8X8X32_LRN9_INT8_0

#ifdef CDP_8X8X64_LRN3_INT8_0
#define HWPE_NVDLA_TRACE cdp_8x8x64_lrn3_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/cdp_8x8x64_lrn3_int8_0/cdp_8x8x64_lrn3_int8_0.h"
#define TRACE_INPUT_DATA cdp_8x8x64_lrn3_int8_0_data
#define TRACE_OUTPUT_SPACE cdp_8x8x64_lrn3_int8_0_space
#endif // CDP_8X8X64_LRN3_INT8_0

#ifdef CDP_8X8X64_LRN3_INT8_1
#define HWPE_NVDLA_TRACE cdp_8x8x64_lrn3_int8_1
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/cdp_8x8x64_lrn3_int8_1/cdp_8x8x64_lrn3_int8_1.h"
#define TRACE_INPUT_DATA cdp_8x8x64_lrn3_int8_1_data
#define TRACE_OUTPUT_SPACE cdp_8x8x64_lrn3_int8_1_space
#endif // CDP_8X8X64_LRN3_INT8_1

#ifdef CDP_8X8X64_LRN3_INT8_10
#define HWPE_NVDLA_TRACE cdp_8x8x64_lrn3_int8_10
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/cdp_8x8x64_lrn3_int8_10/cdp_8x8x64_lrn3_int8_10.h"
#define TRACE_INPUT_DATA cdp_8x8x64_lrn3_int8_10_data
#define TRACE_OUTPUT_SPACE cdp_8x8x64_lrn3_int8_10_space
#endif // CDP_8X8X64_LRN3_INT8_10

#ifdef CDP_8X8X64_LRN3_INT8_11
#define HWPE_NVDLA_TRACE cdp_8x8x64_lrn3_int8_11
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/cdp_8x8x64_lrn3_int8_11/cdp_8x8x64_lrn3_int8_11.h"
#define TRACE_INPUT_DATA cdp_8x8x64_lrn3_int8_11_data
#define TRACE_OUTPUT_SPACE cdp_8x8x64_lrn3_int8_11_space
#endif // CDP_8X8X64_LRN3_INT8_11

#ifdef CDP_8X8X64_LRN3_INT8_12
#define HWPE_NVDLA_TRACE cdp_8x8x64_lrn3_int8_12
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/cdp_8x8x64_lrn3_int8_12/cdp_8x8x64_lrn3_int8_12.h"
#define TRACE_INPUT_DATA cdp_8x8x64_lrn3_int8_12_data
#define TRACE_OUTPUT_SPACE cdp_8x8x64_lrn3_int8_12_space
#endif // CDP_8X8X64_LRN3_INT8_12

#ifdef CDP_8X8X64_LRN3_INT8_2
#define HWPE_NVDLA_TRACE cdp_8x8x64_lrn3_int8_2
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/cdp_8x8x64_lrn3_int8_2/cdp_8x8x64_lrn3_int8_2.h"
#define TRACE_INPUT_DATA cdp_8x8x64_lrn3_int8_2_data
#define TRACE_OUTPUT_SPACE cdp_8x8x64_lrn3_int8_2_space
#endif // CDP_8X8X64_LRN3_INT8_2

#ifdef CDP_8X8X64_LRN3_INT8_3
#define HWPE_NVDLA_TRACE cdp_8x8x64_lrn3_int8_3
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/cdp_8x8x64_lrn3_int8_3/cdp_8x8x64_lrn3_int8_3.h"
#define TRACE_INPUT_DATA cdp_8x8x64_lrn3_int8_3_data
#define TRACE_OUTPUT_SPACE cdp_8x8x64_lrn3_int8_3_space
#endif // CDP_8X8X64_LRN3_INT8_3

#ifdef CDP_8X8X64_LRN3_INT8_4
#define HWPE_NVDLA_TRACE cdp_8x8x64_lrn3_int8_4
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/cdp_8x8x64_lrn3_int8_4/cdp_8x8x64_lrn3_int8_4.h"
#define TRACE_INPUT_DATA cdp_8x8x64_lrn3_int8_4_data
#define TRACE_OUTPUT_SPACE cdp_8x8x64_lrn3_int8_4_space
#endif // CDP_8X8X64_LRN3_INT8_4

#ifdef CDP_8X8X64_LRN3_INT8_5
#define HWPE_NVDLA_TRACE cdp_8x8x64_lrn3_int8_5
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/cdp_8x8x64_lrn3_int8_5/cdp_8x8x64_lrn3_int8_5.h"
#define TRACE_INPUT_DATA cdp_8x8x64_lrn3_int8_5_data
#define TRACE_OUTPUT_SPACE cdp_8x8x64_lrn3_int8_5_space
#endif // CDP_8X8X64_LRN3_INT8_5

#ifdef CDP_8X8X64_LRN3_INT8_6
#define HWPE_NVDLA_TRACE cdp_8x8x64_lrn3_int8_6
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/cdp_8x8x64_lrn3_int8_6/cdp_8x8x64_lrn3_int8_6.h"
#define TRACE_INPUT_DATA cdp_8x8x64_lrn3_int8_6_data
#define TRACE_OUTPUT_SPACE cdp_8x8x64_lrn3_int8_6_space
#endif // CDP_8X8X64_LRN3_INT8_6

#ifdef CDP_8X8X64_LRN3_INT8_7
#define HWPE_NVDLA_TRACE cdp_8x8x64_lrn3_int8_7
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/cdp_8x8x64_lrn3_int8_7/cdp_8x8x64_lrn3_int8_7.h"
#define TRACE_INPUT_DATA cdp_8x8x64_lrn3_int8_7_data
#define TRACE_OUTPUT_SPACE cdp_8x8x64_lrn3_int8_7_space
#endif // CDP_8X8X64_LRN3_INT8_7

#ifdef CDP_8X8X64_LRN3_INT8_8
#define HWPE_NVDLA_TRACE cdp_8x8x64_lrn3_int8_8
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/cdp_8x8x64_lrn3_int8_8/cdp_8x8x64_lrn3_int8_8.h"
#define TRACE_INPUT_DATA cdp_8x8x64_lrn3_int8_8_data
#define TRACE_OUTPUT_SPACE cdp_8x8x64_lrn3_int8_8_space
#endif // CDP_8X8X64_LRN3_INT8_8

#ifdef CDP_8X8X64_LRN3_INT8_9
#define HWPE_NVDLA_TRACE cdp_8x8x64_lrn3_int8_9
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/cdp_8x8x64_lrn3_int8_9/cdp_8x8x64_lrn3_int8_9.h"
#define TRACE_INPUT_DATA cdp_8x8x64_lrn3_int8_9_data
#define TRACE_OUTPUT_SPACE cdp_8x8x64_lrn3_int8_9_space
#endif // CDP_8X8X64_LRN3_INT8_9

#ifdef CDP_8X8X64_LRN9_INT8
#define HWPE_NVDLA_TRACE cdp_8x8x64_lrn9_int8
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/cdp_8x8x64_lrn9_int8/cdp_8x8x64_lrn9_int8.h"
#define TRACE_INPUT_DATA cdp_8x8x64_lrn9_int8_data
#define TRACE_OUTPUT_SPACE cdp_8x8x64_lrn9_int8_space
#endif // CDP_8X8X64_LRN9_INT8

#ifdef DC_13X15X64_5X3X64X16_INT8_0
#define HWPE_NVDLA_TRACE dc_13x15x64_5x3x64x16_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/dc_13x15x64_5x3x64x16_int8_0/dc_13x15x64_5x3x64x16_int8_0.h"
#define TRACE_INPUT_DATA dc_13x15x64_5x3x64x16_int8_0_data
#define TRACE_INPUT_DATA_1 dc_13x15x64_5x3x64x16_int8_0_data_1
#define TRACE_OUTPUT_SPACE dc_13x15x64_5x3x64x16_int8_0_space
#endif // DC_13X15X64_5X3X64X16_INT8_0

#ifdef DC_14X7X49_3X4X49X32_INT8_0
#define HWPE_NVDLA_TRACE dc_14x7x49_3x4x49x32_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/dc_14x7x49_3x4x49x32_int8_0/dc_14x7x49_3x4x49x32_int8_0.h"
#define TRACE_INPUT_DATA dc_14x7x49_3x4x49x32_int8_0_data
#define TRACE_INPUT_DATA_1 dc_14x7x49_3x4x49x32_int8_0_data_1
#define TRACE_OUTPUT_SPACE dc_14x7x49_3x4x49x32_int8_0_space
#endif // DC_14X7X49_3X4X49X32_INT8_0

#ifdef DC_1X1X8_1X1X8X1_INT8_0
#define HWPE_NVDLA_TRACE dc_1x1x8_1x1x8x1_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/dc_1x1x8_1x1x8x1_int8_0/dc_1x1x8_1x1x8x1_int8_0.h"
#define TRACE_INPUT_DATA dc_1x1x8_1x1x8x1_int8_0_data
#define TRACE_INPUT_DATA_1 dc_1x1x8_1x1x8x1_int8_0_data_1
#define TRACE_OUTPUT_SPACE dc_1x1x8_1x1x8x1_int8_0_space
#endif // DC_1X1X8_1X1X8X1_INT8_0

#ifdef DC_24X33X55_5X5X55X25_INT8_0
#define HWPE_NVDLA_TRACE dc_24x33x55_5x5x55x25_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/dc_24x33x55_5x5x55x25_int8_0/dc_24x33x55_5x5x55x25_int8_0.h"
#define TRACE_INPUT_DATA dc_24x33x55_5x5x55x25_int8_0_data
#define TRACE_INPUT_DATA_1 dc_24x33x55_5x5x55x25_int8_0_data_1
#define TRACE_OUTPUT_SPACE dc_24x33x55_5x5x55x25_int8_0_space
#endif // DC_24X33X55_5X5X55X25_INT8_0

#ifdef DC_24X44X14_5X3X14X41_INT8_0
#define HWPE_NVDLA_TRACE dc_24x44x14_5x3x14x41_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/dc_24x44x14_5x3x14x41_int8_0/dc_24x44x14_5x3x14x41_int8_0.h"
#define TRACE_INPUT_DATA dc_24x44x14_5x3x14x41_int8_0_data
#define TRACE_INPUT_DATA_1 dc_24x44x14_5x3x14x41_int8_0_data_1
#define TRACE_OUTPUT_SPACE dc_24x44x14_5x3x14x41_int8_0_space
#endif // DC_24X44X14_5X3X14X41_INT8_0

#ifdef DC_32X26X76_6X3X76X16_INT8_0
#define HWPE_NVDLA_TRACE dc_32x26x76_6x3x76x16_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/dc_32x26x76_6x3x76x16_int8_0/dc_32x26x76_6x3x76x16_int8_0.h"
#define TRACE_INPUT_DATA dc_32x26x76_6x3x76x16_int8_0_data
#define TRACE_INPUT_DATA_1 dc_32x26x76_6x3x76x16_int8_0_data_1
#define TRACE_OUTPUT_SPACE dc_32x26x76_6x3x76x16_int8_0_space
#endif // DC_32X26X76_6X3X76X16_INT8_0

#ifdef DC_32X26X76_6X3X76X270_INT8_0
#define HWPE_NVDLA_TRACE dc_32x26x76_6x3x76x270_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/dc_32x26x76_6x3x76x270_int8_0/dc_32x26x76_6x3x76x270_int8_0.h"
#define TRACE_INPUT_DATA dc_32x26x76_6x3x76x270_int8_0_data
#define TRACE_INPUT_DATA_1 dc_32x26x76_6x3x76x270_int8_0_data_1
#define TRACE_OUTPUT_SPACE dc_32x26x76_6x3x76x270_int8_0_space
#endif // DC_32X26X76_6X3X76X270_INT8_0

#ifdef DC_35X22X54_6X8X54X29_INT8_0
#define HWPE_NVDLA_TRACE dc_35x22x54_6x8x54x29_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/dc_35x22x54_6x8x54x29_int8_0/dc_35x22x54_6x8x54x29_int8_0.h"
#define TRACE_INPUT_DATA dc_35x22x54_6x8x54x29_int8_0_data
#define TRACE_INPUT_DATA_1 dc_35x22x54_6x8x54x29_int8_0_data_1
#define TRACE_OUTPUT_SPACE dc_35x22x54_6x8x54x29_int8_0_space
#endif // DC_35X22X54_6X8X54X29_INT8_0

#ifdef DC_4X1X8192_1X1X8192X1_INT8_0
#define HWPE_NVDLA_TRACE dc_4x1x8192_1x1x8192x1_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/dc_4x1x8192_1x1x8192x1_int8_0/dc_4x1x8192_1x1x8192x1_int8_0.h"
#define TRACE_INPUT_DATA dc_4x1x8192_1x1x8192x1_int8_0_data
#define TRACE_INPUT_DATA_1 dc_4x1x8192_1x1x8192x1_int8_0_data_1
#define TRACE_OUTPUT_SPACE dc_4x1x8192_1x1x8192x1_int8_0_space
#endif // DC_4X1X8192_1X1X8192X1_INT8_0

#ifdef DC_6X8X192_3X3X192X32_INT8_0
#define HWPE_NVDLA_TRACE dc_6x8x192_3x3x192x32_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/dc_6x8x192_3x3x192x32_int8_0/dc_6x8x192_3x3x192x32_int8_0.h"
#define TRACE_INPUT_DATA dc_6x8x192_3x3x192x32_int8_0_data
#define TRACE_INPUT_DATA_1 dc_6x8x192_3x3x192x32_int8_0_data_1
#define TRACE_OUTPUT_SPACE dc_6x8x192_3x3x192x32_int8_0_space
#endif // DC_6X8X192_3X3X192X32_INT8_0

#ifdef DC_8192X1X1_2X3X1X41_INT8_0
#define HWPE_NVDLA_TRACE dc_8192x1x1_2x3x1x41_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/dc_8192x1x1_2x3x1x41_int8_0/dc_8192x1x1_2x3x1x41_int8_0.h"
#define TRACE_INPUT_DATA dc_8192x1x1_2x3x1x41_int8_0_data
#define TRACE_INPUT_DATA_1 dc_8192x1x1_2x3x1x41_int8_0_data_1
#define TRACE_OUTPUT_SPACE dc_8192x1x1_2x3x1x41_int8_0_space
#endif // DC_8192X1X1_2X3X1X41_INT8_0

#ifdef DC_8X16X128_3X3X128X32_INT8
#define HWPE_NVDLA_TRACE dc_8x16x128_3x3x128x32_int8
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/dc_8x16x128_3x3x128x32_int8/dc_8x16x128_3x3x128x32_int8.h"
#define TRACE_INPUT_DATA dc_8x16x128_3x3x128x32_int8_data
#define TRACE_INPUT_DATA_1 dc_8x16x128_3x3x128x32_int8_data_1
#define TRACE_OUTPUT_SPACE dc_8x16x128_3x3x128x32_int8_space
#endif // DC_8X16X128_3X3X128X32_INT8

#ifdef DC_8X8X36_4X4X36X16_DILATION_INT8_0
#define HWPE_NVDLA_TRACE dc_8x8x36_4x4x36x16_dilation_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/dc_8x8x36_4x4x36x16_dilation_int8_0/dc_8x8x36_4x4x36x16_dilation_int8_0.h"
#define TRACE_INPUT_DATA dc_8x8x36_4x4x36x16_dilation_int8_0_data
#define TRACE_INPUT_DATA_1 dc_8x8x36_4x4x36x16_dilation_int8_0_data_1
#define TRACE_OUTPUT_SPACE dc_8x8x36_4x4x36x16_dilation_int8_0_space
#endif // DC_8X8X36_4X4X36X16_DILATION_INT8_0

#ifdef IMG_51X96X4_1X10X4X32_A8B8G8R8_INT8_0
#define HWPE_NVDLA_TRACE img_51x96x4_1x10x4x32_A8B8G8R8_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/img_51x96x4_1x10x4x32_A8B8G8R8_int8_0/img_51x96x4_1x10x4x32_A8B8G8R8_int8_0.h"
#define TRACE_INPUT_DATA img_51x96x4_1x10x4x32_A8B8G8R8_int8_0_data
#define TRACE_INPUT_DATA_1 img_51x96x4_1x10x4x32_A8B8G8R8_int8_0_data_1
#define TRACE_OUTPUT_SPACE img_51x96x4_1x10x4x32_A8B8G8R8_int8_0_space
#endif // IMG_51X96X4_1X10X4X32_A8B8G8R8_INT8_0

#ifdef IMG_51X96X4_1X10X4X32_A8R8G8B8_INT8_0
#define HWPE_NVDLA_TRACE img_51x96x4_1x10x4x32_A8R8G8B8_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/img_51x96x4_1x10x4x32_A8R8G8B8_int8_0/img_51x96x4_1x10x4x32_A8R8G8B8_int8_0.h"
#define TRACE_INPUT_DATA img_51x96x4_1x10x4x32_A8R8G8B8_int8_0_data
#define TRACE_INPUT_DATA_1 img_51x96x4_1x10x4x32_A8R8G8B8_int8_0_data_1
#define TRACE_OUTPUT_SPACE img_51x96x4_1x10x4x32_A8R8G8B8_int8_0_space
#endif // IMG_51X96X4_1X10X4X32_A8R8G8B8_INT8_0

#ifdef IMG_51X96X4_1X10X4X32_A8Y8U8V8_INT8_0
#define HWPE_NVDLA_TRACE img_51x96x4_1x10x4x32_A8Y8U8V8_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/img_51x96x4_1x10x4x32_A8Y8U8V8_int8_0/img_51x96x4_1x10x4x32_A8Y8U8V8_int8_0.h"
#define TRACE_INPUT_DATA img_51x96x4_1x10x4x32_A8Y8U8V8_int8_0_data
#define TRACE_INPUT_DATA_1 img_51x96x4_1x10x4x32_A8Y8U8V8_int8_0_data_1
#define TRACE_OUTPUT_SPACE img_51x96x4_1x10x4x32_A8Y8U8V8_int8_0_space
#endif // IMG_51X96X4_1X10X4X32_A8Y8U8V8_INT8_0

#ifdef IMG_51X96X4_1X10X4X32_B8G8R8A8_INT8_0
#define HWPE_NVDLA_TRACE img_51x96x4_1x10x4x32_B8G8R8A8_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/img_51x96x4_1x10x4x32_B8G8R8A8_int8_0/img_51x96x4_1x10x4x32_B8G8R8A8_int8_0.h"
#define TRACE_INPUT_DATA img_51x96x4_1x10x4x32_B8G8R8A8_int8_0_data
#define TRACE_INPUT_DATA_1 img_51x96x4_1x10x4x32_B8G8R8A8_int8_0_data_1
#define TRACE_OUTPUT_SPACE img_51x96x4_1x10x4x32_B8G8R8A8_int8_0_space
#endif // IMG_51X96X4_1X10X4X32_B8G8R8A8_INT8_0

#ifdef IMG_51X96X4_1X10X4X32_B8G8R8X8_INT8_0
#define HWPE_NVDLA_TRACE img_51x96x4_1x10x4x32_B8G8R8X8_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/img_51x96x4_1x10x4x32_B8G8R8X8_int8_0/img_51x96x4_1x10x4x32_B8G8R8X8_int8_0.h"
#define TRACE_INPUT_DATA img_51x96x4_1x10x4x32_B8G8R8X8_int8_0_data
#define TRACE_INPUT_DATA_1 img_51x96x4_1x10x4x32_B8G8R8X8_int8_0_data_1
#define TRACE_OUTPUT_SPACE img_51x96x4_1x10x4x32_B8G8R8X8_int8_0_space
#endif // IMG_51X96X4_1X10X4X32_B8G8R8X8_INT8_0

#ifdef IMG_51X96X4_1X10X4X32_R8G8B8A8_INT8_0
#define HWPE_NVDLA_TRACE img_51x96x4_1x10x4x32_R8G8B8A8_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/img_51x96x4_1x10x4x32_R8G8B8A8_int8_0/img_51x96x4_1x10x4x32_R8G8B8A8_int8_0.h"
#define TRACE_INPUT_DATA img_51x96x4_1x10x4x32_R8G8B8A8_int8_0_data
#define TRACE_INPUT_DATA_1 img_51x96x4_1x10x4x32_R8G8B8A8_int8_0_data_1
#define TRACE_OUTPUT_SPACE img_51x96x4_1x10x4x32_R8G8B8A8_int8_0_space
#endif // IMG_51X96X4_1X10X4X32_R8G8B8A8_INT8_0

#ifdef IMG_51X96X4_1X10X4X32_R8G8B8X8_INT8_0
#define HWPE_NVDLA_TRACE img_51x96x4_1x10x4x32_R8G8B8X8_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/img_51x96x4_1x10x4x32_R8G8B8X8_int8_0/img_51x96x4_1x10x4x32_R8G8B8X8_int8_0.h"
#define TRACE_INPUT_DATA img_51x96x4_1x10x4x32_R8G8B8X8_int8_0_data
#define TRACE_INPUT_DATA_1 img_51x96x4_1x10x4x32_R8G8B8X8_int8_0_data_1
#define TRACE_OUTPUT_SPACE img_51x96x4_1x10x4x32_R8G8B8X8_int8_0_space
#endif // IMG_51X96X4_1X10X4X32_R8G8B8X8_INT8_0

#ifdef IMG_51X96X4_1X10X4X32_V8U8Y8A8_INT8_0
#define HWPE_NVDLA_TRACE img_51x96x4_1x10x4x32_V8U8Y8A8_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/img_51x96x4_1x10x4x32_V8U8Y8A8_int8_0/img_51x96x4_1x10x4x32_V8U8Y8A8_int8_0.h"
#define TRACE_INPUT_DATA img_51x96x4_1x10x4x32_V8U8Y8A8_int8_0_data
#define TRACE_INPUT_DATA_1 img_51x96x4_1x10x4x32_V8U8Y8A8_int8_0_data_1
#define TRACE_OUTPUT_SPACE img_51x96x4_1x10x4x32_V8U8Y8A8_int8_0_space
#endif // IMG_51X96X4_1X10X4X32_V8U8Y8A8_INT8_0

#ifdef IMG_51X96X4_1X10X4X32_X8B8G8R8_INT8_0
#define HWPE_NVDLA_TRACE img_51x96x4_1x10x4x32_X8B8G8R8_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/img_51x96x4_1x10x4x32_X8B8G8R8_int8_0/img_51x96x4_1x10x4x32_X8B8G8R8_int8_0.h"
#define TRACE_INPUT_DATA img_51x96x4_1x10x4x32_X8B8G8R8_int8_0_data
#define TRACE_INPUT_DATA_1 img_51x96x4_1x10x4x32_X8B8G8R8_int8_0_data_1
#define TRACE_OUTPUT_SPACE img_51x96x4_1x10x4x32_X8B8G8R8_int8_0_space
#endif // IMG_51X96X4_1X10X4X32_X8B8G8R8_INT8_0

#ifdef IMG_51X96X4_1X10X4X32_X8R8G8B8_INT8_0
#define HWPE_NVDLA_TRACE img_51x96x4_1x10x4x32_X8R8G8B8_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/img_51x96x4_1x10x4x32_X8R8G8B8_int8_0/img_51x96x4_1x10x4x32_X8R8G8B8_int8_0.h"
#define TRACE_INPUT_DATA img_51x96x4_1x10x4x32_X8R8G8B8_int8_0_data
#define TRACE_INPUT_DATA_1 img_51x96x4_1x10x4x32_X8R8G8B8_int8_0_data_1
#define TRACE_OUTPUT_SPACE img_51x96x4_1x10x4x32_X8R8G8B8_int8_0_space
#endif // IMG_51X96X4_1X10X4X32_X8R8G8B8_INT8_0

#ifdef PDP_12X9X19_8X3_AVE_INT8_0
#define HWPE_NVDLA_TRACE pdp_12x9x19_8x3_ave_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/pdp_12x9x19_8x3_ave_int8_0/pdp_12x9x19_8x3_ave_int8_0.h"
#define TRACE_INPUT_DATA pdp_12x9x19_8x3_ave_int8_0_data
#define TRACE_OUTPUT_SPACE pdp_12x9x19_8x3_ave_int8_0_space
#endif // PDP_12X9X19_8X3_AVE_INT8_0

#ifdef PDP_16X6X16_4X2_SPLIT_MAX_INT8_0
#define HWPE_NVDLA_TRACE pdp_16x6x16_4x2_split_max_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/pdp_16x6x16_4x2_split_max_int8_0/pdp_16x6x16_4x2_split_max_int8_0.h"
#define TRACE_INPUT_DATA pdp_16x6x16_4x2_split_max_int8_0_data
#define TRACE_OUTPUT_SPACE pdp_16x6x16_4x2_split_max_int8_0_space
#endif // PDP_16X6X16_4X2_SPLIT_MAX_INT8_0

#ifdef PDP_1X1X1_3X3_AVE_INT8_0
#define HWPE_NVDLA_TRACE pdp_1x1x1_3x3_ave_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/pdp_1x1x1_3x3_ave_int8_0/pdp_1x1x1_3x3_ave_int8_0.h"
#define TRACE_INPUT_DATA pdp_1x1x1_3x3_ave_int8_0_data
#define TRACE_OUTPUT_SPACE pdp_1x1x1_3x3_ave_int8_0_space
#endif // PDP_1X1X1_3X3_AVE_INT8_0

#ifdef PDP_1X3X8_8X8_AVE_INT8_0
#define HWPE_NVDLA_TRACE pdp_1x3x8_8x8_ave_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/pdp_1x3x8_8x8_ave_int8_0/pdp_1x3x8_8x8_ave_int8_0.h"
#define TRACE_INPUT_DATA pdp_1x3x8_8x8_ave_int8_0_data
#define TRACE_OUTPUT_SPACE pdp_1x3x8_8x8_ave_int8_0_space
#endif // PDP_1X3X8_8X8_AVE_INT8_0

#ifdef PDP_24X16X1_8X8_AVE_INT8_0
#define HWPE_NVDLA_TRACE pdp_24x16x1_8x8_ave_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/pdp_24x16x1_8x8_ave_int8_0/pdp_24x16x1_8x8_ave_int8_0.h"
#define TRACE_INPUT_DATA pdp_24x16x1_8x8_ave_int8_0_data
#define TRACE_OUTPUT_SPACE pdp_24x16x1_8x8_ave_int8_0_space
#endif // PDP_24X16X1_8X8_AVE_INT8_0

#ifdef PDP_28X28X8_2X2_MAX_INT8_0
#define HWPE_NVDLA_TRACE pdp_28x28x8_2x2_max_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/pdp_28x28x8_2x2_max_int8_0/pdp_28x28x8_2x2_max_int8_0.h"
#define TRACE_INPUT_DATA pdp_28x28x8_2x2_max_int8_0_data
#define TRACE_OUTPUT_SPACE pdp_28x28x8_2x2_max_int8_0_space
#endif // PDP_28X28X8_2X2_MAX_INT8_0

#ifdef PDP_5X7X8_4X1_SPLIT_MAX_INT8_0
#define HWPE_NVDLA_TRACE pdp_5x7x8_4x1_split_max_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/pdp_5x7x8_4x1_split_max_int8_0/pdp_5x7x8_4x1_split_max_int8_0.h"
#define TRACE_INPUT_DATA pdp_5x7x8_4x1_split_max_int8_0_data
#define TRACE_OUTPUT_SPACE pdp_5x7x8_4x1_split_max_int8_0_space
#endif // PDP_5X7X8_4X1_SPLIT_MAX_INT8_0

#ifdef PDP_7X9X10_3X3_INT8
#define HWPE_NVDLA_TRACE pdp_7x9x10_3x3_int8
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/pdp_7x9x10_3x3_int8/pdp_7x9x10_3x3_int8.h"
#define TRACE_INPUT_DATA pdp_7x9x10_3x3_int8_data
#define TRACE_OUTPUT_SPACE pdp_7x9x10_3x3_int8_space
#endif // PDP_7X9X10_3X3_INT8

#ifdef PDP_8X8X32_1X1_INT8_0
#define HWPE_NVDLA_TRACE pdp_8x8x32_1x1_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/pdp_8x8x32_1x1_int8_0/pdp_8x8x32_1x1_int8_0.h"
#define TRACE_OUTPUT_SPACE pdp_8x8x32_1x1_int8_0_space
#define TRACE_INPUT_DATA pdp_8x8x32_1x1_int8_0_data
#endif // PDP_8X8X32_1X1_INT8_0

#ifdef PDP_8X8X32_1X1_INT8_1
#define HWPE_NVDLA_TRACE pdp_8x8x32_1x1_int8_1
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/pdp_8x8x32_1x1_int8_1/pdp_8x8x32_1x1_int8_1.h"
#define TRACE_INPUT_DATA pdp_8x8x32_1x1_int8_1_data
#define TRACE_INPUT_DATA_1 pdp_8x8x32_1x1_int8_1_data_1
#endif // PDP_8X8X32_1X1_INT8_1

#ifdef PDP_8X8X64_2X2_AVE_INT8_0
#define HWPE_NVDLA_TRACE pdp_8x8x64_2x2_ave_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/pdp_8x8x64_2x2_ave_int8_0/pdp_8x8x64_2x2_ave_int8_0.h"
#define TRACE_INPUT_DATA pdp_8x8x64_2x2_ave_int8_0_data
#define TRACE_OUTPUT_SPACE pdp_8x8x64_2x2_ave_int8_0_space
#endif // PDP_8X8X64_2X2_AVE_INT8_0

#ifdef PDP_8X8X64_2X2_INT8
#define HWPE_NVDLA_TRACE pdp_8x8x64_2x2_int8
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/pdp_8x8x64_2x2_int8/pdp_8x8x64_2x2_int8.h"
#define TRACE_INPUT_DATA pdp_8x8x64_2x2_int8_data
#define TRACE_OUTPUT_SPACE pdp_8x8x64_2x2_int8_space
#endif // PDP_8X8X64_2X2_INT8

#ifdef PDP_8X8X64_2X2_MIN_INT8_0
#define HWPE_NVDLA_TRACE pdp_8x8x64_2x2_min_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/pdp_8x8x64_2x2_min_int8_0/pdp_8x8x64_2x2_min_int8_0.h"
#define TRACE_INPUT_DATA pdp_8x8x64_2x2_min_int8_0_data
#define TRACE_OUTPUT_SPACE pdp_8x8x64_2x2_min_int8_0_space
#endif // PDP_8X8X64_2X2_MIN_INT8_0

#ifdef PDP_8X9X19_3X3_AVE_INT8_0
#define HWPE_NVDLA_TRACE pdp_8x9x19_3x3_ave_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/pdp_8x9x19_3x3_ave_int8_0/pdp_8x9x19_3x3_ave_int8_0.h"
#define TRACE_INPUT_DATA pdp_8x9x19_3x3_ave_int8_0_data
#define TRACE_OUTPUT_SPACE pdp_8x9x19_3x3_ave_int8_0_space
#endif // PDP_8X9X19_3X3_AVE_INT8_0

#ifdef PDP_8X9X19_3X3_AVE_INT8_1
#define HWPE_NVDLA_TRACE pdp_8x9x19_3x3_ave_int8_1
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/pdp_8x9x19_3x3_ave_int8_1/pdp_8x9x19_3x3_ave_int8_1.h"
#define TRACE_INPUT_DATA pdp_8x9x19_3x3_ave_int8_1_data
#define TRACE_OUTPUT_SPACE pdp_8x9x19_3x3_ave_int8_1_space
#endif // PDP_8X9X19_3X3_AVE_INT8_1

#ifdef SDP_1X1X1_PASS_THROUGH_INT8
#define HWPE_NVDLA_TRACE sdp_1x1x1_pass_through_int8
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/sdp_1x1x1_pass_through_int8/sdp_1x1x1_pass_through_int8.h"
#define TRACE_INPUT_DATA sdp_1x1x1_pass_through_int8_data
#define TRACE_OUTPUT_SPACE sdp_1x1x1_pass_through_int8_space
#endif // SDP_1X1X1_PASS_THROUGH_INT8

#ifdef SDP_1X1X8_PASS_THROUGH_INT8_0
#define HWPE_NVDLA_TRACE sdp_1x1x8_pass_through_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/sdp_1x1x8_pass_through_int8_0/sdp_1x1x8_pass_through_int8_0.h"
#define TRACE_INPUT_DATA sdp_1x1x8_pass_through_int8_0_data
#define TRACE_OUTPUT_SPACE sdp_1x1x8_pass_through_int8_0_space
#endif // SDP_1X1X8_PASS_THROUGH_INT8_0

#ifdef SDP_1X8192X1_PASS_THROUGH_INT8_0
#define HWPE_NVDLA_TRACE sdp_1x8192x1_pass_through_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/sdp_1x8192x1_pass_through_int8_0/sdp_1x8192x1_pass_through_int8_0.h"
#define TRACE_INPUT_DATA sdp_1x8192x1_pass_through_int8_0_data
#define TRACE_OUTPUT_SPACE sdp_1x8192x1_pass_through_int8_0_space
#endif // SDP_1X8192X1_PASS_THROUGH_INT8_0

#ifdef SDP_23X13X42_BS_INT8_MEM_0
#define HWPE_NVDLA_TRACE sdp_23x13x42_bs_int8_mem_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/sdp_23x13x42_bs_int8_mem_0/sdp_23x13x42_bs_int8_mem_0.h"
#define TRACE_INPUT_DATA sdp_23x13x42_bs_int8_mem_0_data
#define TRACE_INPUT_DATA_1 sdp_23x13x42_bs_int8_mem_0_data_1
#define TRACE_OUTPUT_SPACE sdp_23x13x42_bs_int8_mem_0_space
#endif // SDP_23X13X42_BS_INT8_MEM_0

#ifdef SDP_3X3X32_EW_LO_LIN_INT8
#define HWPE_NVDLA_TRACE sdp_3x3x32_ew_lo_lin_int8
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/sdp_3x3x32_ew_lo_lin_int8/sdp_3x3x32_ew_lo_lin_int8.h"
#define TRACE_INPUT_DATA sdp_3x3x32_ew_lo_lin_int8_data
#define TRACE_OUTPUT_SPACE sdp_3x3x32_ew_lo_lin_int8_space
#endif // SDP_3X3X32_EW_LO_LIN_INT8

#ifdef SDP_3X3X33_BN_INT8_MEM_0
#define HWPE_NVDLA_TRACE sdp_3x3x33_bn_int8_mem_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/sdp_3x3x33_bn_int8_mem_0/sdp_3x3x33_bn_int8_mem_0.h"
#define TRACE_INPUT_DATA sdp_3x3x33_bn_int8_mem_0_data
#define TRACE_INPUT_DATA_1 sdp_3x3x33_bn_int8_mem_0_data_1
#define TRACE_OUTPUT_SPACE sdp_3x3x33_bn_int8_mem_0_space
#endif // SDP_3X3X33_BN_INT8_MEM_0

#ifdef SDP_3X3X33_BN_INT8_REG_0
#define HWPE_NVDLA_TRACE sdp_3x3x33_bn_int8_reg_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/sdp_3x3x33_bn_int8_reg_0/sdp_3x3x33_bn_int8_reg_0.h"
#define TRACE_INPUT_DATA sdp_3x3x33_bn_int8_reg_0_data
#define TRACE_OUTPUT_SPACE sdp_3x3x33_bn_int8_reg_0_space
#endif // SDP_3X3X33_BN_INT8_REG_0

#ifdef SDP_3X3X33_BN_INT8_REG_1
#define HWPE_NVDLA_TRACE sdp_3x3x33_bn_int8_reg_1
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/sdp_3x3x33_bn_int8_reg_1/sdp_3x3x33_bn_int8_reg_1.h"
#define TRACE_INPUT_DATA sdp_3x3x33_bn_int8_reg_1_data
#define TRACE_OUTPUT_SPACE sdp_3x3x33_bn_int8_reg_1_space
#endif // SDP_3X3X33_BN_INT8_REG_1

#ifdef SDP_3X3X33_BN_INT8_REG_2
#define HWPE_NVDLA_TRACE sdp_3x3x33_bn_int8_reg_2
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/sdp_3x3x33_bn_int8_reg_2/sdp_3x3x33_bn_int8_reg_2.h"
#define TRACE_INPUT_DATA sdp_3x3x33_bn_int8_reg_2_data
#define TRACE_OUTPUT_SPACE sdp_3x3x33_bn_int8_reg_2_space
#endif // SDP_3X3X33_BN_INT8_REG_2

#ifdef SDP_3X3X33_BN_INT8_REG_3
#define HWPE_NVDLA_TRACE sdp_3x3x33_bn_int8_reg_3
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/sdp_3x3x33_bn_int8_reg_3/sdp_3x3x33_bn_int8_reg_3.h"
#define TRACE_INPUT_DATA sdp_3x3x33_bn_int8_reg_3_data
#define TRACE_OUTPUT_SPACE sdp_3x3x33_bn_int8_reg_3_space
#endif // SDP_3X3X33_BN_INT8_REG_3

#ifdef SDP_3X3X33_BS_BN_INT8_0
#define HWPE_NVDLA_TRACE sdp_3x3x33_bs_bn_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/sdp_3x3x33_bs_bn_int8_0/sdp_3x3x33_bs_bn_int8_0.h"
#define TRACE_INPUT_DATA sdp_3x3x33_bs_bn_int8_0_data
#define TRACE_OUTPUT_SPACE sdp_3x3x33_bs_bn_int8_0_space
#endif // SDP_3X3X33_BS_BN_INT8_0

#ifdef SDP_3X3X33_BS_BN_INT8_1
#define HWPE_NVDLA_TRACE sdp_3x3x33_bs_bn_int8_1
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/sdp_3x3x33_bs_bn_int8_1/sdp_3x3x33_bs_bn_int8_1.h"
#define TRACE_INPUT_DATA sdp_3x3x33_bs_bn_int8_1_data
#define TRACE_OUTPUT_SPACE sdp_3x3x33_bs_bn_int8_1_space
#endif // SDP_3X3X33_BS_BN_INT8_1

#ifdef SDP_3X3X33_BS_INT8_REG_0
#define HWPE_NVDLA_TRACE sdp_3x3x33_bs_int8_reg_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/sdp_3x3x33_bs_int8_reg_0/sdp_3x3x33_bs_int8_reg_0.h"
#define TRACE_INPUT_DATA sdp_3x3x33_bs_int8_reg_0_data
#define TRACE_OUTPUT_SPACE sdp_3x3x33_bs_int8_reg_0_space
#endif // SDP_3X3X33_BS_INT8_REG_0

#ifdef SDP_3X3X33_BS_INT8_REG_1
#define HWPE_NVDLA_TRACE sdp_3x3x33_bs_int8_reg_1
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/sdp_3x3x33_bs_int8_reg_1/sdp_3x3x33_bs_int8_reg_1.h"
#define TRACE_INPUT_DATA sdp_3x3x33_bs_int8_reg_1_data
#define TRACE_OUTPUT_SPACE sdp_3x3x33_bs_int8_reg_1_space
#endif // SDP_3X3X33_BS_INT8_REG_1

#ifdef SDP_3X3X33_EW_INT8_REG_0
#define HWPE_NVDLA_TRACE sdp_3x3x33_ew_int8_reg_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/sdp_3x3x33_ew_int8_reg_0/sdp_3x3x33_ew_int8_reg_0.h"
#define TRACE_INPUT_DATA sdp_3x3x33_ew_int8_reg_0_data
#define TRACE_OUTPUT_SPACE sdp_3x3x33_ew_int8_reg_0_space
#endif // SDP_3X3X33_EW_INT8_REG_0

#ifdef SDP_3X3X33_EW_LE_EXP_INT8
#define HWPE_NVDLA_TRACE sdp_3x3x33_ew_le_exp_int8
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/sdp_3x3x33_ew_le_exp_int8/sdp_3x3x33_ew_le_exp_int8.h"
#define TRACE_INPUT_DATA sdp_3x3x33_ew_le_exp_int8_data
#define TRACE_OUTPUT_SPACE sdp_3x3x33_ew_le_exp_int8_space
#endif // SDP_3X3X33_EW_LE_EXP_INT8

#ifdef SDP_3X3X33_EW_LE_LIN_INT8
#define HWPE_NVDLA_TRACE sdp_3x3x33_ew_le_lin_int8
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/sdp_3x3x33_ew_le_lin_int8/sdp_3x3x33_ew_le_lin_int8.h"
#define TRACE_INPUT_DATA sdp_3x3x33_ew_le_lin_int8_data
#define TRACE_OUTPUT_SPACE sdp_3x3x33_ew_le_lin_int8_space
#endif // SDP_3X3X33_EW_LE_LIN_INT8

#ifdef SDP_4X1X8192_PASS_THROUGH_INT8_0
#define HWPE_NVDLA_TRACE sdp_4x1x8192_pass_through_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/sdp_4x1x8192_pass_through_int8_0/sdp_4x1x8192_pass_through_int8_0.h"
#define TRACE_INPUT_DATA sdp_4x1x8192_pass_through_int8_0_data
#define TRACE_OUTPUT_SPACE sdp_4x1x8192_pass_through_int8_0_space
#endif // SDP_4X1X8192_PASS_THROUGH_INT8_0

#ifdef SDP_4X22X42_BYPASS_INT8
#define HWPE_NVDLA_TRACE sdp_4x22x42_bypass_int8
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/sdp_4x22x42_bypass_int8/sdp_4x22x42_bypass_int8.h"
#define TRACE_INPUT_DATA sdp_4x22x42_bypass_int8_data
#define TRACE_OUTPUT_SPACE sdp_4x22x42_bypass_int8_space
#endif // SDP_4X22X42_BYPASS_INT8

#ifdef SDP_5X24X18_BS_INT8_MEM_0
#define HWPE_NVDLA_TRACE sdp_5x24x18_bs_int8_mem_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/sdp_5x24x18_bs_int8_mem_0/sdp_5x24x18_bs_int8_mem_0.h"
#define TRACE_INPUT_DATA sdp_5x24x18_bs_int8_mem_0_data
#define TRACE_INPUT_DATA_1 sdp_5x24x18_bs_int8_mem_0_data_1
#define TRACE_OUTPUT_SPACE sdp_5x24x18_bs_int8_mem_0_space
#endif // SDP_5X24X18_BS_INT8_MEM_0

#ifdef SDP_8192X1X1_PASS_THROUGH_INT8_0
#define HWPE_NVDLA_TRACE sdp_8192x1x1_pass_through_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/sdp_8192x1x1_pass_through_int8_0/sdp_8192x1x1_pass_through_int8_0.h"
#define TRACE_INPUT_DATA sdp_8192x1x1_pass_through_int8_0_data
#define TRACE_OUTPUT_SPACE sdp_8192x1x1_pass_through_int8_0_space
#endif // SDP_8192X1X1_PASS_THROUGH_INT8_0

#ifdef SDP_8X8X32_BYPASS_INT8_0
#define HWPE_NVDLA_TRACE sdp_8x8x32_bypass_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/sdp_8x8x32_bypass_int8_0/sdp_8x8x32_bypass_int8_0.h"
#define TRACE_INPUT_DATA sdp_8x8x32_bypass_int8_0_data
#define TRACE_OUTPUT_SPACE sdp_8x8x32_bypass_int8_0_space
#endif // SDP_8X8X32_BYPASS_INT8_0

#ifdef SDP_8X8X32_BYPASS_INT8_1
#define HWPE_NVDLA_TRACE sdp_8x8x32_bypass_int8_1
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/sdp_8x8x32_bypass_int8_1/sdp_8x8x32_bypass_int8_1.h"
#define TRACE_INPUT_DATA sdp_8x8x32_bypass_int8_1_data
#define TRACE_INPUT_DATA_1 sdp_8x8x32_bypass_int8_1_data_1
#endif // SDP_8X8X32_BYPASS_INT8_1

#ifdef SDP_PDP_32X16X32_PASS_THROUGH_INT8_0
#define HWPE_NVDLA_TRACE sdp_pdp_32x16x32_pass_through_int8_0
#include "/home/pulp_nvdla/hwpe_nvdla/nvdla_hw/verif/tests/trace_tests/nv_small/sdp_pdp_32x16x32_pass_through_int8_0/sdp_pdp_32x16x32_pass_through_int8_0.h"
#define TRACE_INPUT_DATA sdp_pdp_32x16x32_pass_through_int8_0_data
#define TRACE_OUTPUT_SPACE sdp_pdp_32x16x32_pass_through_int8_0_space
#endif // SDP_PDP_32X16X32_PASS_THROUGH_INT8_0


#ifndef HWPE_NVDLA_TRACE
#error "No trace test specified!"
#endif // HWPE_NVDLA_TRACE

#define _TRACE_CONCAT(first, second) first ## second
#define _TRACE_EVAL_CONCAT(x, y) _TRACE_CONCAT(x, y)
#define _TRACE_QUOTE(arg) #arg
#define _TRACE_STR(macro) _TRACE_QUOTE(macro)

#define TRACE_NAME _TRACE_STR(HWPE_NVDLA_TRACE)
#define TRACE_LOG(format, ...) printf(TRACE_NAME " - " format "\n", ##__VA_ARGS__)
#define TRACE_SETUP_REGISTERS _TRACE_EVAL_CONCAT(HWPE_NVDLA_TRACE, _setup_registers)
#define TRACE_FINISH _TRACE_EVAL_CONCAT(HWPE_NVDLA_TRACE, _finish)

#endif // HWPE_NVDLA_ALL_TRACES_H
