
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED 17)

find_package(verilator HINTS $ENV{VERILATOR_ROOT} ${VERILATOR_ROOT})
if (NOT verilator_FOUND)
  message(FATAL_ERROR "Verilator was not found. Either install it, or set the VERILATOR_ROOT environment variable")
endif()


option(HWPE_NVDLA_USE_SYSTEMC      "Use SystemC simulations (CURRENTLY NOT SUPPORTED!)"    OFF)

set(HWPE_NVDLA_ROOT_DIR ${CMAKE_CURRENT_LIST_DIR}/../..)
set(HWPE_NVDLA_SOURCE_DIR ${HWPE_NVDLA_ROOT_DIR}/src)
set(HWPE_NVDLA_INTF_DIR ${HWPE_NVDLA_ROOT_DIR}/intf)
set(HWPE_NVDLA_TEST_DIR ${HWPE_NVDLA_ROOT_DIR}/test)
set(HWPE_NVDLA_TEST_SOURCES_DIR ${HWPE_NVDLA_TEST_DIR}/src)
set(HWPE_NVDLA_VERILATOR_DIR ${HWPE_NVDLA_TEST_DIR}/verilator)
set(HWPE_NVDLA_VERILATOR_COMMON_DIR_BASE ${HWPE_NVDLA_VERILATOR_DIR}/common)

if(HWPE_NVDLA_USE_SYSTEMC)
    set(HWPE_NVDLA_VERILATOR_COMMON_DIR ${HWPE_NVDLA_VERILATOR_COMMON_DIR_BASE}/sc) 
else()
    set(HWPE_NVDLA_VERILATOR_COMMON_DIR ${HWPE_NVDLA_VERILATOR_COMMON_DIR_BASE}/cc) 
endif(HWPE_NVDLA_USE_SYSTEMC)

file(GLOB HWPE_NVDLA_ALL_SOURCES    "${HWPE_NVDLA_SRC_DIR}/*.sv")
file(GLOB HWPE_NVDLA_ALL_INTERFACES "${HWPE_NVDLA_INTF_DIR}/*.sv")